name: 'mosaix-metricbeat'
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true


#==================== Elasticsearch template setting ==========================
setup.template.name: "mosaix-metricbeat-%{+yyyy.MM.dd}"
setup.template.pattern: "mosaix-metricbeat-*"

setup.template.settings:
 index.number_of_shards: 1
 index.codec: best_compression

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  index: "mosaix-metricbeat-%{+yyyy.MM.dd}"
  hosts: "${ELASTIC_HOST}"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASS}"


#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag or the `setup` command.
setup.dashboards.enabled: true
setup.dashboards.index: "mosaix-metricbeat-*"
#============================== Kibana =====================================
# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.

setup.kibana:
  host: "${KIBANA_HOST}"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASS}"